# Generated by Django 4.0.5 on 2023-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spironellohome', '0003_marketplaceproducts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproducts',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
