# Generated by Django 4.0.5 on 2023-01-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spironellohome', '0005_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.CharField(max_length=4)),
                ('car_version', models.CharField(max_length=100)),
                ('has_gnc', models.BooleanField()),
                ('is_it_new', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('phone_prefix', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.RenameModel(
            old_name='MarketPlaceProducts',
            new_name='InsuranceList',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='quote',
            name='products',
            field=models.ManyToManyField(to='spironellohome.insurancelist'),
        ),
        migrations.AddField(
            model_name='car',
            name='fast_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spironellohome.quote'),
        ),
    ]
