# Generated by Django 4.1.5 on 2023-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0006_car_quote_remove_user_products_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metros_cuadrados_cubiertos", models.IntegerField()),
                ("tipo_de_vivienda", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="car",
            name="fast_quote",
        ),
        migrations.RemoveField(
            model_name="car",
            name="is_it_new",
        ),
        migrations.AddField(
            model_name="car",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="insurancelist",
            name="product_abreviation",
            field=models.CharField(default="No abreviation", max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_version",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="has_gnc",
            field=models.BooleanField(default=False),
        ),
    ]
