# Generated by Django 4.1.5 on 2023-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spironellohome",
            "0007_house_remove_car_fast_quote_remove_car_is_it_new_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancelist",
            name="product_abreviation",
            field=models.CharField(default="No abreviation", max_length=100),
        ),
    ]
