# Generated by Django 4.1.5 on 2023-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0010_alter_car_has_gnc_alter_car_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_year",
            field=models.IntegerField(max_length=4),
        ),
    ]
