# Generated by Django 4.1.5 on 2023-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0011_alter_car_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancelist",
            name="product_abreviation",
            field=models.CharField(max_length=100),
        ),
    ]
