# Generated by Django 4.1.5 on 2023-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0013_alter_insurancelist_product_abreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_brand",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="product_abreviation",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="visitordata",
            name="surname",
            field=models.CharField(max_length=100),
        ),
    ]
