# Generated by Django 4.1.5 on 2023-02-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0017_alter_insurancelist_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancelist",
            name="product_abreviation",
        ),
    ]
