# Generated by Django 4.1.5 on 2023-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0019_remove_visitordata_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitordata",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
