# Generated by Django 4.1.5 on 2023-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0021_remove_visitordata_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitordata",
            name="zip_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
