# Generated by Django 4.1.5 on 2023-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0022_alter_visitordata_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancelist",
            name="description",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="slug",
            field=models.SlugField(blank=True, max_length=3550, null=True),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
