# Generated by Django 4.1.5 on 2023-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0023_alter_insurancelist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancelist",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="slug",
            field=models.SlugField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
