# Generated by Django 4.1.5 on 2023-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0024_alter_insurancelist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="about_text",
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="description",
            field=models.CharField(max_length=3000),
        ),
    ]
