# Generated by Django 4.1.5 on 2023-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0025_alter_footer_about_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="metros_cuadrados_cubiertos",
            field=models.CharField(max_length=100),
        ),
    ]
