# Generated by Django 4.1.5 on 2023-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0026_alter_house_metros_cuadrados_cubiertos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="has_gnc",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_new",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="insurancelist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
