# Generated by Django 4.1.5 on 2023-02-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0030_alter_car_has_gnc_alter_car_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancelist",
            name="product_abreviation",
            field=models.CharField(default="other", max_length=20),
        ),
    ]
