# Generated by Django 4.1.5 on 2023-02-08 22:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0031_insurancelist_product_abreviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("summary", ckeditor.fields.RichTextField(default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("image_description", models.CharField(blank=True, max_length=255)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("body", ckeditor.fields.RichTextField(default="")),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
