# Generated by Django 4.1.5 on 2023-02-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0034_section"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Section",
        ),
    ]
