# Generated by Django 4.1.5 on 2023-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0036_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_caucion", models.CharField(max_length=100)),
                ("comentarios_adicionales", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destino", models.CharField(max_length=100)),
                ("fecha_de_salida", models.DateField()),
                ("fecha_de_regreso", models.DateField()),
                ("cantidad_de_pasajeros", models.IntegerField()),
            ],
        ),
    ]
