# Generated by Django 4.1.5 on 2023-02-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spironellohome", "0037_caucion_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningarticles",
            name="body",
        ),
    ]
